setup/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.projectimp.urls')),
]

apps/projectimp/models.py
from django.db import models

class IdentificacaoEmpresa(models.Model):
    nome_empresa = models.CharField(max_length=200, null=False, blank=False) 
    email_empresa = models.EmailField(max_length=200, null=False, blank=False)
    fone_empresa = models.CharField(max_length=200, null=False, blank=False)
    cnpj_empresa = models.CharField(max_length=200, null=False, blank=False)
        
    def __str__(self):
       return self.nome_empresa

class CadastroGrupo(models.Model):
    nome_grupo = models.CharField(max_length=200, null=False, blank=False) 
    ordem_grupo = models.IntegerField(null=False, blank=False)
    ativo = models.BooleanField(default=False)

    def __str__(self):
       return self.nome_grupo

class CadastroSubGrupo(models.Model):
    nome_subgrupo = models.CharField(max_length=200, null=False, blank=False) 
    ordem_subgrupo = models.IntegerField(null=False, blank=False)
    ativo = models.BooleanField(default=False)
    nome_grupo = models.ForeignKey(
        to=CadastroGrupo,
        on_delete=models.SET_NULL,
        null=True,
        blank=False,
        related_name="grupo"
    )

    def __str__(self):
       return self.nome_subgrupo
    
class CadastroItem(models.Model):
    TIPO_CHOICES = [
        ('list', 'Lista'),
        ('checkbox', 'Caixa de Seleção'),
        ('descritivo', 'Descritivo'),
    ]
     
    nome_item = models.CharField(max_length=200, null=False, blank=False) 
    ordem_item = models.IntegerField(null=False, blank=False)
    ativo = models.BooleanField(default=False)
    tipo = models.CharField(max_length=20, choices=TIPO_CHOICES)
    contador = models.IntegerField(null=False, blank=False)
    Opcional = models.BooleanField(default=False)
    Unidade =models.IntegerField(null=False, blank=False)
    nome_subgrupo = models.ForeignKey(
        to=CadastroSubGrupo,
        on_delete=models.SET_NULL,
        null=True,
        blank=False,
        related_name="subgrupo"
    )
    lista = models.ForeignKey('Lista', on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
       return self.nome_item
    
class CadastroRespostaItem(models.Model):
    resposta_item = models.CharField(max_length=200, null=False, blank=False)
    nome_item = models.ForeignKey(
        to=CadastroItem,
        on_delete=models.SET_NULL,
        null=True,
        blank=False,
        related_name="item"
    )

    def __str__(self):
       return self.resposta_item
    
class Lista(models.Model):
    nome = models.CharField(max_length=100)
    ordem = models.IntegerField(default=0)
    ativo = models.BooleanField(default=True)

    def __str__(self):
        return self.nome

class OpcaoLista(models.Model):
    lista = models.ForeignKey(Lista, on_delete=models.CASCADE)
    descricao = models.CharField(max_length=100)
    ordem = models.IntegerField(default=0)
    ativo = models.BooleanField(default=True)

    def __str__(self):
        return self.descricao

templates/cadastro.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastro de Usuário</title>
    <link rel="stylesheet" href="{% static 'styles/style.css' %}"> <!-- Importar arquivo de estilos CSS -->
</head>
<body>
    <div class="container">
        <h1>Identificação da Empresa para Diagnóstico</h1>
        <form action="submit.php" method="post">
            <label for="nome">Nome Completo:</label>
            <input type="text" id="nome" name="nome" required>

            <label for="email">E-mail:</label>
            <input type="email" id="email" name="email" required>

            <label for="Fone/WhatApp">Telefone:</label>
            <input type="tel" id="telefone" name="telefone" required>

            <label for="CNPJ">CNPJ:</label>
            <input type="text" id="CNPJ" name="CNPJ" required>

            <button type="submit">Cadastrar</button>
        </form>
    </div>
</body>
</html>

templates/cadastro_grupo.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastro de Usuário</title>
    <link rel="stylesheet" href="{% static 'styles/bootstrap/css/bootstrap.min.css' %}"> <!-- Importar arquivo de estilos do Bootstrap -->
    <style>
        /* Aplique um espaçamento inferior aos campos do formulário */
        .form-group {
            margin-bottom: 20px;
        }
        /* Estilo para o formulário */
        .custom-form {
            max-width: 800px; /* Largura máxima do formulário */
            margin: 0 auto; /* Centralizar o formulário na tela */
            padding: 20px; /* Espaçamento interno do formulário */
            border: 1px solid #ccc; /* Borda do formulário */
            border-radius: 5px; /* Borda arredondada */
            background-color: #f9f9f9; /* Cor de fundo do formulário */
        }
    </style>
</head>
<body>
    <div class="container">
        <h1 class="text-center">Cadastro de Grupos</h1>
        <div class="mx-auto custom-form"> <!-- Centralize e defina uma largura máxima para o formulário -->
            <form action="{% url 'salvar_grupo' %}" method="POST">
                {% csrf_token %}
                {% for field in form.visible_fields %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {% if field.field.widget.input_type != 'checkbox' %}
                        {{ field }}
                    {% else %}
                        <div class="form-check">
                            {{ field }}
                            <label class="form-check-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
                        </div>
                    {% endif %}
                </div>
                {% endfor %}
                <div class="text-right"> <!-- Alinhe o botão à direita -->
                    <button type="submit" class="btn btn-success">Salvar</button>
                </div>
            </form>
        </div>
    </div>
</body>
</html>

templates/crud_resposta_item.html
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Nova Página</title>
</head>
<body>
    <h1>Nova Página</h1>
    
    <form method="POST">
        {% csrf_token %}
        {% for subgrupo, itens in itens_por_subgrupo.items %}
        <h2>{{ subgrupo.nome_subgrupo }}</h2>
        {% for item in itens %}
        <label for="id_item_{{ item.id }}">{{ item.nome_item }}</label>
        {% if item.tipo == 'checkbox' %}
        <input type="checkbox" id="id_item_{{ item.id }}" name="item_{{ item.id }}">
        {% elif item.tipo == 'descritivo' %}
        <input type="text" id="id_item_{{ item.id }}" name="item_{{ item.id }}">
        {% elif item.tipo == 'lista' %}
        <select id="id_item_{{ item.id }}" name="item_{{ item.id }}">
            {% for opcao in item.lista.opcaolista_set.all %}
            <option value="{{ opcao.id }}">{{ opcao.descricao }}</option>
            {% endfor %}
        </select>
        {% endif %}
        {% endfor %}
        {% endfor %}
        <button type="submit">Salvar</button>
    </form>
</body>
</html>

templates/detalhes_grupo.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ grupo.nome_grupo }}</title>
    <!-- Inclua seus arquivos de CSS aqui -->
    <link rel="stylesheet" href="{% static 'styles/bootstrap/css/bootstrap.min.css' %}"> <!-- Importe o arquivo CSS do Bootstrap -->
    <link rel="stylesheet" href="{% static 'styles/style.css' %}"> <!-- Importe o seu arquivo CSS personalizado -->
    <style>
        /* Estilos adicionais aqui */
    </style>
</head>
<body class="body">
    <div class="container">
        <h1 class="text-center">{{ grupo.nome_grupo }}</h1>
        
        <!-- Iterando sobre cada subgrupo -->
        {% for subgrupo, itens in itens_por_subgrupo.items %}
        <div class="mx-auto custom-form">
            <h2>{{ subgrupo.nome_subgrupo }}</h2>
            
            
            <form id="form-{{ subgrupo.id }}" method="POST"> 
                {% csrf_token %} 
                {% for item in itens %}
                <div class="form-group">
                    <label for="{{ item.nome_item }}">{{ item.nome_item }}</label>
                    {% if item.tipo == 'checkbox' %}
                        <!-- Renderizar um campo checkbox -->
                        <input type="checkbox" name="{{ item.nome_item }}" class="form-check-input">
                    {% elif item.tipo == 'descritivo' %}
                        <!-- Renderizar um campo de texto -->
                        <input type="text" name="{{ item.nome_item }}" class="form-control">
                    {% else %}
                        <!-- Renderizar um campo de lista -->
                        <select name="{{ item.nome_item }}" class="form-control">
                            {% for opcao in item.lista.opcaolista_set.all %}
                                <option value="{{ opcao.id }}">{{ opcao.descricao }}</option>
                            {% endfor %}
                        </select>
                    {% endif %}
                </div>
                {% endfor %}
            </form>
        </div>
        {% endfor %}
        <!-- Botões de navegação -->
        <div class="btn-container">
            <div class="btn-group">
                {% if grupo_anterior_id %}
                <a href="{% url 'detalhes_grupo' grupo_id=grupo_anterior_id %}" class="btn btn-primary btn-left">Voltar</a>
                {% endif %}
                {% if proximo_grupo_id %}
                <a href="{% url 'detalhes_grupo' grupo_id=proximo_grupo_id %}" class="btn btn-primary btn-right">Avançar</a>
                {% endif %}
            </div>
        </div>
    </div>    
    <script>
        function submitForm(grupoId) {
            console.log('Botão clicado para o grupo ID:', grupoId);   
        }
    </script>
</body>
</html>

templates/resposta.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Listar Itens</title>
    <link rel="stylesheet" href="{% static 'styles/bootstrap/css/bootstrap.min.css' %}"> <!-- Importar arquivo de estilos do Bootstrap -->
    <style>
        /* Aplique um espaçamento inferior aos campos do formulário */
        .form-group {
            margin-bottom: 20px;
        }
        /* Estilo para o formulário */
        .custom-form {
            max-width: 800px; /* Largura máxima do formulário */
            margin: 0 auto; /* Centralizar o formulário na tela */
            padding: 20px; /* Espaçamento interno do formulário */
            border: 1px solid #ccc; /* Borda do formulário */
            border-radius: 5px; /* Borda arredondada */
            background-color: #f9f9f9; /* Cor de fundo do formulário */
            margin-bottom: 30px; /* Adiciona margem inferior para separar os formulários */
        }
        /* Estilo para o título do subgrupo */
        .subgrupo-title {
            font-size: 1.5em;
            margin-top: 30px;
            margin-bottom: 10px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1 class="text-center">Lista de Itens Cadastrados</h1>
        {% for subgrupo, itens in itens_por_subgrupo.items %}
        <div class="mx-auto custom-form">
            <h2 class="subgrupo-title">{{ subgrupo.nome_subgrupo }}</h2>
            <form>
                {% for item in itens %}
                <div class="form-group">
                    <label for="{{ item.nome_item }}">{{ item.nome_item }}</label>
                    {% if item.tipo == 'checkbox' %}
                        <!-- Renderizar um campo checkbox -->
                        <input type="checkbox" name="{{ item.nome_item }}" class="form-check-input">
                    {% else %}
                        <!-- Renderizar outros tipos de campos -->
                        <input type="text" name="{{ item.nome_item }}" class="form-control">
                    {% endif %}
                </div>
                {% endfor %}
            </form>
        </div>
        {% endfor %}
        <div class="text-right"> <!-- Alinhe o botão à direita -->
            <button type="submit" class="btn btn-success">Salvar</button>
        </div>
    </div>    
</body>
</html>